version: "3"

services:
  postgresql:
    container_name: database_service
    image: databasetest
    ports:
      - 5432:5432

    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  react-frontend:
    container_name: frontend_service
    image: frontend
    ports:
      - 5000:5000

  react-api:
    container_name: api_service
    image: api-test
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database_service:5432/reactdb2 
      - TEST_DATABASE_URL=postgresql://postgres:postgres@database_service:5432/reactdb2
      - REQUESTS_ORIGIN="*"
      - APP_SECRET=iigMnxy7y7dFJppmd3JgZRzOUYLgmjaXX
    
    depends_on:
      - postgresql

         

