version: "3"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment: 
      DATABASE_URL: postgresql://localhost/bucketlist_testdb
      APP_SECRET: iigMnxy7y7dFJppmd3JgZRzOUYLgmjaXX 
      REQUESTS_ORIGIN: "*"
      TEST_DATABASE_URL: postgresql://localhost/bucketlist_testdb

     
  web:
    image: jkarage/dockerizingtest:test1
    ports:
      - "4000:80"
    networks:
      - webnet
      
networks:
  webnet:
